###Job Name
#PBS -N height_mean
### Project code
#PBS -A uncs0044
#PBS -l walltime=12:00:00
#PBS -q main
### Merge output and error files
#PBS -j oe
#PBS -k eod
#PBS -l select=1
### Send email on abort, begin and end
#PBS -m abe
### Specify mail recipient
#PBS -M legetker@ncsu.edu

export TMPDIR=/glade/derecho/scratch/$USER/temp
mkdir -p $TMPDIR

### Run the executable
module load conda
conda activate my-clone
python ./calc_500mb_mean.py
